const data = [
    {
        id: "4514",
        createdby: "uid20",
        created: "2023-04-04T12:15:00Z",
        title: "How can I ensure that the content generated by the AI is plagiarism-free?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "new",
        last: "12 min",
        replys:[
            {
                from: "user",
                text: "Hi, chatbot. What's your name?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Hello! I'm Gbot, a friendly AI chatbot. How can I assist you today?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "What's the weather like in New York City today?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "I'm sorry, I don't have access to real-time data. You can check a weather website or app for the latest updates.",
                time:"10:11 AM"
            },
            {
                from: "user",
                text: "Can you help me with a math problem? What's 345 multiplied by 67?",
                time:"10:14 AM"
            },
            {
                from: "support",
                text: "Sure! 345 multiplied by 67 is 23,115.",
                time:"10:18 AM"
            },
            {
                from: "user",
                text: "I need a recipe for spaghetti carbonara. Can you help?",
                time:"10:24 AM"
            },
            {
                from: "support",
                text: "Of course! Here's a simple spaghetti carbonara recipe: [recipe link]",
                time:"10:32 AM"
            },
            {
                from: "user",
                text: "I'm in the mood for a comedy movie. Any recommendations?",
                time:"10:43 AM"
            },
            {
                from: "support",
                text: "How about watching 'The Grand Budapest Hotel'? It's a hilarious comedy with a unique visual style.",
                time:"10:55 AM"
            },
            {
                from: "user",
                text: "I have a headache. What should I do to relieve it?",
                time:"10:57 AM"
            },
            {
                from: "support",
                text: "I'm not a doctor, but you can try drinking water, resting in a quiet room, or taking a pain reliever like ibuprofen. If it persists, consider consulting a healthcare professional.",
                time:"10:58 AM"
            },
            {
                from: "user",
                text: "Can you explain Einstein's theory of relativity in simple terms?",
                time:"10:59 AM"
            }
        ]
    },
    {
        id: "6301",
        createdby: "uid2",
        created: "2023-04-04T12:15:00Z",
        title: "Can the AI content generator create content in different languages ?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "active",
        last: "1 hour",
        replys:[
            {
                from: "user",
                text: "How can I ensure that the content generated by the AI is plagiarism-free?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Ensuring plagiarism-free content is crucial. Firstly, it's essential to understand what constitutes plagiarism. Have you encountered any specific challenges or concerns in this regard?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "Well, I worry that the AI might inadvertently produce content that resembles existing material without proper attribution. How can I prevent that?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "That's a valid concern. One effective approach is to utilize reputable sources when gathering information and to paraphrase or summarize the content in your own words. Additionally, always remember to cite sources properly if you're directly quoting or using specific information.",
                time:"10:11 AM"
            },
            {
                from: "user",
                text: "That makes sense. Are there any tools or resources you'd recommend for checking plagiarism?",
                time:"10:14 AM"
            },
            {
                from: "support",
                text: "Yes, indeed. There are several online tools available for checking plagiarism, such as Turnitin, Grammarly, and Copyscape. These tools compare your text against a vast database of existing content to identify any similarities.",
                time:"10:18 AM"
            },
            {
                from: "user",
                text: "Great, I'll look into those. Is there anything else I should keep in mind to ensure originality in the content generated by AI?",
                time:"10:24 AM"
            },
            {
                from: "support",
                text: "It's also essential to review and edit the content thoroughly after it's generated. Look for any similarities to existing material and make necessary adjustments. Additionally, try to customize the content and add your own unique insights to make it original.",
                time:"10:32 AM"
            },
            {
                from: "user",
                text: "Thank you for the helpful advice! I'll be sure to implement these strategies to ensure plagiarism-free content.",
                time:"10:43 AM"
            },
            {
                from: "support",
                text: "You're welcome! If you have any further questions or need assistance along the way, feel free to ask.",
                time:"10:55 AM"
            }
        ]
    },
    {
        id: "5435",
        createdby: "uid16",
        created: "2023-04-04T12:15:00Z",
        title: "The content generated by the AI seems to be low quality. Can this be improved?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "active",
        last: "3 hours",
        replys:[
            {
                from: "user",
                text: "How can I ensure that the content generated by the AI is plagiarism-free?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Ensuring plagiarism-free content is crucial. Firstly, it's essential to understand what constitutes plagiarism. Have you encountered any specific challenges or concerns in this regard?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "Well, I worry that the AI might inadvertently produce content that resembles existing material without proper attribution. How can I prevent that?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "That's a valid concern. One effective approach is to utilize reputable sources when gathering information and to paraphrase or summarize the content in your own words. Additionally, always remember to cite sources properly if you're directly quoting or using specific information.",
                time:"10:11 AM"
            }
        ]
    },
    {
        id: "3541",
        createdby: "uid8",
        created: "2023-04-04T12:15:00Z",
        title: "The AI content generator is giving me inaccurate results. What should I do?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "8 hours",
        replys:[
            {
                from: "user",
                text: "Well, I worry that the AI might inadvertently produce content that resembles existing material without proper attribution. How can I prevent that?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "Yes, indeed. There are several online tools available for checking plagiarism, such as Turnitin, Grammarly, and Copyscape. These tools compare your text against a vast database of existing content to identify any similarities.",
                time:"10:18 AM"
            },
            {
                from: "user",
                text: "Great, I'll look into those. Is there anything else I should keep in mind to ensure originality in the content generated by AI?",
                time:"10:24 AM"
            },
            {
                from: "support",
                text: "It's also essential to review and edit the content thoroughly after it's generated. Look for any similarities to existing material and make necessary adjustments. Additionally, try to customize the content and add your own unique insights to make it original.",
                time:"10:32 AM"
            },
        ]
    },
    {
        id: "5854",
        createdby: "uid19",
        created: "2023-04-04T12:15:00Z",
        title: "I am having trouble integrating the AI content generator with my website. Can you assist me with this?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "1 days",
        replys:[
            {
                from: "user",
                text: "Hi, chatbot. What's your name?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Hello! I'm Gbot, a friendly AI chatbot. How can I assist you today?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "What's the weather like in New York City today?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "I'm sorry, I don't have access to real-time data. You can check a weather website or app for the latest updates.",
                time:"10:11 AM"
            },
            {
                from: "user",
                text: "Can you help me with a math problem? What's 345 multiplied by 67?",
                time:"10:14 AM"
            },
        ]
    },
    {
        id: "9844",
        createdby: "uid12",
        created: "2023-04-04T12:15:00Z",
        title: "Is there a way to increase the variety of topics covered by the AI content generator?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "2 days",
        replys:[
            {
                from: "user",
                text: "I'm in the mood for a comedy movie. Any recommendations?",
                time:"10:43 AM"
            },
            {
                from: "support",
                text: "How about watching 'The Grand Budapest Hotel'? It's a hilarious comedy with a unique visual style.",
                time:"10:55 AM"
            },
            {
                from: "user",
                text: "I have a headache. What should I do to relieve it?",
                time:"10:57 AM"
            },
            {
                from: "support",
                text: "I'm not a doctor, but you can try drinking water, resting in a quiet room, or taking a pain reliever like ibuprofen. If it persists, consider consulting a healthcare professional.",
                time:"10:58 AM"
            },
            {
                from: "user",
                text: "Can you explain Einstein's theory of relativity in simple terms?",
                time:"10:59 AM"
            }
        ]
    },
    {
        id: "0872",
        createdby: "uid11",
        created: "2023-04-04T12:15:00Z",
        title: "I am not satisfied with the tone and style of the content generated by the AI. Can I customize this?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "active",
        last: "3 days",
        replys:[
            {
                from: "user",
                text: "How can I ensure that the content generated by the AI is plagiarism-free?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Ensuring plagiarism-free content is crucial. Firstly, it's essential to understand what constitutes plagiarism. Have you encountered any specific challenges or concerns in this regard?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "Great, I'll look into those. Is there anything else I should keep in mind to ensure originality in the content generated by AI?",
                time:"10:24 AM"
            },
            {
                from: "support",
                text: "It's also essential to review and edit the content thoroughly after it's generated. Look for any similarities to existing material and make necessary adjustments. Additionally, try to customize the content and add your own unique insights to make it original.",
                time:"10:32 AM"
            },
        ]
    },
    {
        id: "7651",
        createdby: "uid15",
        created: "2023-04-04T12:15:00Z",
        title: "How can I track the performance of the AI content generator in terms of engagement and conversions?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "4 days",
        replys:[
            {
                from: "user",
                text: "Hi, chatbot. What's your name?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Hello! I'm Gbot, a friendly AI chatbot. How can I assist you today?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "What's the weather like in New York City today?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "I'm sorry, I don't have access to real-time data. You can check a weather website or app for the latest updates.",
                time:"10:11 AM"
            },
            {
                from: "user",
                text: "Can you help me with a math problem? What's 345 multiplied by 67?",
                time:"10:14 AM"
            },
        ]
    },
    {
        id: "4519",
        createdby: "uid20",
        created: "2023-04-04T12:15:00Z",
        title: "How can I ensure that the content generated by the AI is plagiarism-free?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "5 days",
        replys:[
            {
                from: "user",
                text: "Hi, chatbot. What's your name?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Hello! I'm Gbot, a friendly AI chatbot. How can I assist you today?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "What's the weather like in New York City today?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "I'm sorry, I don't have access to real-time data. You can check a weather website or app for the latest updates.",
                time:"10:11 AM"
            },
            {
                from: "user",
                text: "Can you help me with a math problem? What's 345 multiplied by 67?",
                time:"10:14 AM"
            },
            {
                from: "support",
                text: "Sure! 345 multiplied by 67 is 23,115.",
                time:"10:18 AM"
            },
            {
                from: "user",
                text: "I need a recipe for spaghetti carbonara. Can you help?",
                time:"10:24 AM"
            },
            {
                from: "support",
                text: "Of course! Here's a simple spaghetti carbonara recipe: [recipe link]",
                time:"10:32 AM"
            },
            {
                from: "user",
                text: "I'm in the mood for a comedy movie. Any recommendations?",
                time:"10:43 AM"
            },
            {
                from: "support",
                text: "How about watching 'The Grand Budapest Hotel'? It's a hilarious comedy with a unique visual style.",
                time:"10:55 AM"
            },
            {
                from: "user",
                text: "I have a headache. What should I do to relieve it?",
                time:"10:57 AM"
            },
            {
                from: "support",
                text: "I'm not a doctor, but you can try drinking water, resting in a quiet room, or taking a pain reliever like ibuprofen. If it persists, consider consulting a healthcare professional.",
                time:"10:58 AM"
            },
            {
                from: "user",
                text: "Can you explain Einstein's theory of relativity in simple terms?",
                time:"10:59 AM"
            }
        ]
    },
    {
        id: "6310",
        createdby: "uid2",
        created: "2023-04-04T12:15:00Z",
        title: "Can the AI content generator create content in different languages ?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "active",
        last: "6 days",
        replys:[
            {
                from: "user",
                text: "How can I ensure that the content generated by the AI is plagiarism-free?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Ensuring plagiarism-free content is crucial. Firstly, it's essential to understand what constitutes plagiarism. Have you encountered any specific challenges or concerns in this regard?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "Well, I worry that the AI might inadvertently produce content that resembles existing material without proper attribution. How can I prevent that?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "That's a valid concern. One effective approach is to utilize reputable sources when gathering information and to paraphrase or summarize the content in your own words. Additionally, always remember to cite sources properly if you're directly quoting or using specific information.",
                time:"10:11 AM"
            },
            {
                from: "user",
                text: "That makes sense. Are there any tools or resources you'd recommend for checking plagiarism?",
                time:"10:14 AM"
            },
            {
                from: "support",
                text: "Yes, indeed. There are several online tools available for checking plagiarism, such as Turnitin, Grammarly, and Copyscape. These tools compare your text against a vast database of existing content to identify any similarities.",
                time:"10:18 AM"
            },
            {
                from: "user",
                text: "Great, I'll look into those. Is there anything else I should keep in mind to ensure originality in the content generated by AI?",
                time:"10:24 AM"
            },
            {
                from: "support",
                text: "It's also essential to review and edit the content thoroughly after it's generated. Look for any similarities to existing material and make necessary adjustments. Additionally, try to customize the content and add your own unique insights to make it original.",
                time:"10:32 AM"
            },
            {
                from: "user",
                text: "Thank you for the helpful advice! I'll be sure to implement these strategies to ensure plagiarism-free content.",
                time:"10:43 AM"
            },
            {
                from: "support",
                text: "You're welcome! If you have any further questions or need assistance along the way, feel free to ask.",
                time:"10:55 AM"
            }
        ]
    },
    {
        id: "5445",
        createdby: "uid16",
        created: "2023-04-04T12:15:00Z",
        title: "The content generated by the AI seems to be low quality. Can this be improved?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "1 week",
        replys:[
            {
                from: "user",
                text: "How can I ensure that the content generated by the AI is plagiarism-free?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Ensuring plagiarism-free content is crucial. Firstly, it's essential to understand what constitutes plagiarism. Have you encountered any specific challenges or concerns in this regard?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "Well, I worry that the AI might inadvertently produce content that resembles existing material without proper attribution. How can I prevent that?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "That's a valid concern. One effective approach is to utilize reputable sources when gathering information and to paraphrase or summarize the content in your own words. Additionally, always remember to cite sources properly if you're directly quoting or using specific information.",
                time:"10:11 AM"
            }
        ]
    },
    {
        id: "3941",
        createdby: "uid8",
        created: "2023-04-04T12:15:00Z",
        title: "The AI content generator is giving me inaccurate results. What should I do?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "2 weeks",
        replys:[
            {
                from: "user",
                text: "Well, I worry that the AI might inadvertently produce content that resembles existing material without proper attribution. How can I prevent that?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "Yes, indeed. There are several online tools available for checking plagiarism, such as Turnitin, Grammarly, and Copyscape. These tools compare your text against a vast database of existing content to identify any similarities.",
                time:"10:18 AM"
            },
            {
                from: "user",
                text: "Great, I'll look into those. Is there anything else I should keep in mind to ensure originality in the content generated by AI?",
                time:"10:24 AM"
            },
            {
                from: "support",
                text: "It's also essential to review and edit the content thoroughly after it's generated. Look for any similarities to existing material and make necessary adjustments. Additionally, try to customize the content and add your own unique insights to make it original.",
                time:"10:32 AM"
            },
        ]
    },
    {
        id: "5154",
        createdby: "uid19",
        created: "2023-04-04T12:15:00Z",
        title: "I am having trouble integrating the AI content generator with my website. Can you assist me with this?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "3 weeks",
        replys:[
            {
                from: "user",
                text: "Hi, chatbot. What's your name?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Hello! I'm Gbot, a friendly AI chatbot. How can I assist you today?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "What's the weather like in New York City today?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "I'm sorry, I don't have access to real-time data. You can check a weather website or app for the latest updates.",
                time:"10:11 AM"
            },
            {
                from: "user",
                text: "Can you help me with a math problem? What's 345 multiplied by 67?",
                time:"10:14 AM"
            },
        ]
    },
    {
        id: "8844",
        createdby: "uid12",
        created: "2023-04-04T12:15:00Z",
        title: "Is there a way to increase the variety of topics covered by the AI content generator?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "4 weeks",
        replys:[
            {
                from: "user",
                text: "I'm in the mood for a comedy movie. Any recommendations?",
                time:"10:43 AM"
            },
            {
                from: "support",
                text: "How about watching 'The Grand Budapest Hotel'? It's a hilarious comedy with a unique visual style.",
                time:"10:55 AM"
            },
            {
                from: "user",
                text: "I have a headache. What should I do to relieve it?",
                time:"10:57 AM"
            },
            {
                from: "support",
                text: "I'm not a doctor, but you can try drinking water, resting in a quiet room, or taking a pain reliever like ibuprofen. If it persists, consider consulting a healthcare professional.",
                time:"10:58 AM"
            },
            {
                from: "user",
                text: "Can you explain Einstein's theory of relativity in simple terms?",
                time:"10:59 AM"
            }
        ]
    },
    {
        id: "1872",
        createdby: "uid11",
        created: "2023-04-04T12:15:00Z",
        title: "I am not satisfied with the tone and style of the content generated by the AI. Can I customize this?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "1 month",
        replys:[
            {
                from: "user",
                text: "How can I ensure that the content generated by the AI is plagiarism-free?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Ensuring plagiarism-free content is crucial. Firstly, it's essential to understand what constitutes plagiarism. Have you encountered any specific challenges or concerns in this regard?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "Great, I'll look into those. Is there anything else I should keep in mind to ensure originality in the content generated by AI?",
                time:"10:24 AM"
            },
            {
                from: "support",
                text: "It's also essential to review and edit the content thoroughly after it's generated. Look for any similarities to existing material and make necessary adjustments. Additionally, try to customize the content and add your own unique insights to make it original.",
                time:"10:32 AM"
            },
        ]
    },
    {
        id: "0651",
        createdby: "uid15",
        created: "2023-04-04T12:15:00Z",
        title: "How can I track the performance of the AI content generator in terms of engagement and conversions?",
        tags: ["plagiarism", "issue"],
        asigned: ["uid3", "uid11"],
        status: "closed",
        last: "2 month",
        replys:[
            {
                from: "user",
                text: "Hi, chatbot. What's your name?",
                time:"1 days ago"
            },
            {
                from: "support",
                text: "Hello! I'm Gbot, a friendly AI chatbot. How can I assist you today?",
                time:"10:05 AM"
            },
            {
                from: "user",
                text: "What's the weather like in New York City today?",
                time:"10:08 AM"
            },
            {
                from: "support",
                text: "I'm sorry, I don't have access to real-time data. You can check a weather website or app for the latest updates.",
                time:"10:11 AM"
            },
            {
                from: "user",
                text: "Can you help me with a math problem? What's 345 multiplied by 67?",
                time:"10:14 AM"
            },
        ]
    },
];

export default data;
