const data = [
    {
        id: "uid1",
        name: "John Doe",
        email: "johndoe@example.com",
        age: 35,
        avatar: "/images/avatar/thumb/1.jpg",
        joined: "2022-04-01T08:00:00Z",
        phone: "+1 555-555-5555",
        status: "active",
        plan: "Free",
        language: "en",
        country: "US",
        role: "User",
    },
    {
        id: "uid2",
        name: "Jane Smith",
        email: "janesmith@example.com",
        age: 27,
        avatar: "/images/avatar/thumb/2.jpg",
        joined: "2022-04-02T10:30:00Z",
        phone: "+44 123-456-7890",
        status: "active",
        plan: "Free",
        language: "en",
        country: "GB",
        role: "User",
    },
    {
        id: "uid3",
        name: "David Lee",
        email: "davidlee@example.com",
        age: 42,
        avatar: "/images/avatar/thumb/3.jpg",
        joined: "2022-04-03T16:45:00Z",
        phone: "+81 90-1234-5678",
        status: "active",
        plan: "Strater",
        language: "ja",
        country: "JP",
        role: "User",
    },
    {
        id: "uid4",
        name: "Sarah Johnson",
        email: "sarahjohnson@example.com",
        age: 31,
        avatar: "/images/avatar/thumb/4.jpg",
        joined: "2022-04-04T12:15:00Z",
        phone: "+1 555-555-1234",
        status: "suspended",
        plan: "Strater",
        language: "en",
        country: "US",
        role: "User",
    },
    {
        id: "uid5",
        name: "Michael Brown",
        email: "michaelbrown@example.com",
        age: 24,
        avatar: "/images/avatar/thumb/5.jpg",
        joined: "2022-04-05T09:00:00Z",
        phone: "+49 123-456-7890",
        status: "active",
        plan: "Free",
        language: "de",
        country: "DE",
        role: "User",
    },
    {
        id: "uid6",
        name: "Jessica Chen",
        email: "jessicachen@example.com",
        age: 39,
        avatar: "/images/avatar/thumb/6.jpg",
        joined: "2022-04-06T14:30:00Z",
        phone: "+1 555-555-9876",
        status: "suspended",
        plan: "Premium",
        language: "en",
        country: "US",
        role: "User",
    },
    {
        id: "uid7",
        name: "Steven Kim",
        email: "stevenkim@example.com",
        age: 33,
        avatar: "/images/avatar/thumb/7.jpg",
        joined: "2022-04-07T11:45:00Z",
        phone: "+82 10-1234-5678",
        status: "active",
        plan: "Strater",
        language: "ko",
        country: "KR",
        role: "User",
    },
    {
        id: "uid8",
        name: "Emily Davis",
        email: "emilydavis@example.com",
        age: 29,
        avatar: "/images/avatar/thumb/8.jpg",
        joined: "2022-04-08T07:30:00Z",
        phone: "+1 555-555-2468",
        status: "active",
        plan: "Premium",
        language: "en",
        country: "US",
        role: "User",
    },
    {
        id: "uid9",
        name: "Brian Wilson",
        email: "brianwilson@example.com",
        age: 45,
        avatar: "/images/avatar/thumb/9.jpg",
        joined: "2022-04-09T13:15:00Z",
        phone: "+44 789-012-3456",
        status: "active",
        plan: "Premium",
        language: "en",
        country: "GB",
        role: "User",
    },
    {
        id: "uid10",
        name: "Maria Garcia",
        email: "mariagarcia@example.com",
        age: 26,
        avatar: "/images/avatar/thumb/10.jpg",
        joined: "2022-04-10T16:30:00Z",
        phone: "+34 123-456-7890",
        status: "suspended",
        plan: "Free",
        language: "es",
        country: "ES",
        role: "User",
    },
    {
        id: "uid11",
        name: "Daniel Lee",
        email: "daniellee@example.com",
        age: 31,
        avatar: "/images/avatar/thumb/11.jpg",
        joined: "2022-04-11T09:45:00Z",
        phone: "+1 555-555-3698",
        status: "active",
        plan: "Free",
        language: "en",
        country: "US",
        role: "User",
    },
    {
        id: "uid12",
        name: "Amanda Brown",
        email: "amandabrown@example.com",
        age: 28,
        avatar: "/images/avatar/thumb/12.jpg",
        joined: "2022-04-12T12:00:00Z",
        phone: "+44 789-012-3456",
        status: "active",
        plan: "Strater",
        language: "en",
        country: "GB",
        role: "User",
    },
    {
        id: "uid13",
        name: "Luca Rossi",
        email: "lucarossi@example.com",
        age: 37,
        avatar: "/images/avatar/thumb/13.jpg",
        joined: "2022-04-13T15:15:00Z",
        phone: "+39 333-123-4567",
        status: "active",
        plan: "Premium",
        language: "it",
        country: "IT",
        role: "User",
    },
    {
        id: "uid14",
        name: "Samantha Patel",
        email: "samanthapatel@example.com",
        age: 30,
        avatar: "/images/avatar/thumb/14.jpg",
        joined: "2022-04-14T08:30:00Z",
        phone: "+1 555-555-2580",
        status: "active",
        plan: "Free",
        language: "en",
        country: "US",
        role: "User",
    },
    {
        id: "uid15",
        name: "Mohamed Ali",
        email: "mohamedali@example.com",
        age: 33,
        avatar: "/images/avatar/thumb/15.jpg",
        joined: "2022-04-15T11:45:00Z",
        phone: "+20 10-123-4567",
        status: "active",
        plan: "Premium",
        language: "ar",
        country: "EG",
        role: "User",
    },
    {
        id: "uid16",
        name: "Sophie Davis",
        email: "sophiedavis@example.com",
        age: 24,
        avatar: "/images/avatar/thumb/16.jpg",
        joined: "2022-04-16T04:00:00Z",
        phone: "+44 789-123-4567",
        status: "active",
        plan: "Strater",
        language: "en",
        country: "GB",
        role: "User",
    },
    {
        id: "uid17",
        name: "Kenichi Nakamura",
        email: "kenichinakamura@example.com",
        age: 42,
        avatar: "/images/avatar/thumb/17.jpg",
        joined: "2022-04-17T07:15:00Z",
        phone: "+81 90-1234-5678",
        status: "active",
        plan: "Strater",
        language: "ja",
        country: "JP",
        role: "User",
    },
    {
        id: "uid18",
        name: "Eva Hernandez",
        email: "evahernandez@example.com",
        age: 29,
        avatar: "/images/avatar/thumb/18.jpg",
        joined: "2022-04-18T10:30:00Z",
        phone: "+34 678-901-2345",
        status: "suspended",
        plan: "Strater",
        language: "es",
        country: "ES",
        role: "User",
    },
    {
        id: "uid19",
        name: "Maximilian Bauer",
        email: "maxbauer@example.com",
        age: 36,
        avatar: "/images/avatar/thumb/19.jpg",
        joined: "2022-04-19T13:45:00Z",
        phone: "+49 123-456-7890",
        status: "active",
        plan: "Free",
        language: "de",
        country: "DE",
        role: "User",
    },
    {
        id: "uid20",
        name: "Isabella Rossi",
        email: "isabellarossi@example.com",
        age: 27,
        avatar: "/images/avatar/thumb/20.jpg",
        joined: "2022-04-20T17:00:00Z",
        phone: "+39 333-123-4567",
        status: "active",
        plan: "Free",
        language: "it",
        country: "IT",
        role: "User",
    },
];

export default data;
